# Generated by Django 3.1.13 on 2021-11-26 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastro',
            name='school',
            field=models.CharField(choices=[('Junior', 'Junior'), ('Senior', 'Senior'), ('Graduate', 'Graduate')], default='Junior', max_length=25),
        ),
    ]
