# Generated by Django 3.1.13 on 2021-11-26 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20211126_0614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastro',
            name='school',
            field=models.CharField(choices=[('Junior', 'junior'), ('Senior', 'senior'), ('Graduate', 'graduate')], default='Junior', max_length=25),
        ),
    ]
