# Generated by Django 4.1.7 on 2023-03-23 15:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_discipline_semester_grade"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="semester",
            name="qtd",
        ),
        migrations.AddField(
            model_name="semester",
            name="semester",
            field=models.CharField(
                choices=[
                    ("semester_1", "Semester_1"),
                    ("semester_2", "Semester_2"),
                    ("semester_3", "Semester_3"),
                    ("semester_4", "Semester_4"),
                ],
                default=django.utils.timezone.now,
                max_length=200,
            ),
            preserve_default=False,
        ),
    ]
