# Generated by Django 4.0.4 on 2022-05-12 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20211126_0624'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cadastro',
            name='school',
        ),
        migrations.AddField(
            model_name='cadastro',
            name='dev',
            field=models.CharField(choices=[('Junior', 'junior'), ('Pleno', 'pleno'), ('Senior', 'senior')], default='Junior', max_length=25),
        ),
    ]
