# Generated by Django 4.1.7 on 2023-03-23 16:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_remove_semester_qtd_semester_semester"),
    ]

    operations = [
        migrations.AddField(
            model_name="discipline",
            name="createAt",
            field=models.DateTimeField(
                auto_created=True, auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="discipline",
            name="updateAt",
            field=models.DateTimeField(auto_created=True, auto_now=True),
        ),
        migrations.AddField(
            model_name="grade",
            name="createAt",
            field=models.DateTimeField(
                auto_created=True, auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="grade",
            name="updateAt",
            field=models.DateTimeField(auto_created=True, auto_now=True),
        ),
        migrations.AddField(
            model_name="semester",
            name="createAt",
            field=models.DateTimeField(
                auto_created=True, auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="semester",
            name="updateAt",
            field=models.DateTimeField(auto_created=True, auto_now=True),
        ),
        migrations.AddField(
            model_name="user",
            name="createAt",
            field=models.DateTimeField(
                auto_created=True, auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="updateAt",
            field=models.DateTimeField(auto_created=True, auto_now=True),
        ),
    ]
