# Generated by Django 4.1.7 on 2023-03-23 16:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_discipline_createat_discipline_updateat_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="semester",
            name="score",
        ),
        migrations.AddField(
            model_name="grade",
            name="score",
            field=models.DecimalField(decimal_places=2, default=21, max_digits=4),
            preserve_default=False,
        ),
    ]
