# Generated by Django 4.1.7 on 2023-03-23 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_rename_grade_scores"),
    ]

    operations = [
        migrations.AddField(
            model_name="discipline",
            name="student",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.student",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="semester",
            name="discipline",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.discipline",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="semester",
            name="year",
            field=models.CharField(default="12312", max_length=4),
            preserve_default=False,
        ),
    ]
