# Generated by Django 4.1.7 on 2023-03-23 17:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_discipline_student_semester_discipline_semester_year"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="discipline",
            name="student",
        ),
        migrations.AddField(
            model_name="discipline",
            name="student",
            field=models.ManyToManyField(to="core.student"),
        ),
    ]
