# Generated by Django 4.1.7 on 2023-03-24 16:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0009_remove_student_cpf_remove_teacher_description"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="scores",
            options={"verbose_name": "Score", "verbose_name_plural": "Scores"},
        ),
    ]
