# Generated by Django 4.1.7 on 2023-03-26 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_scores_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='semester',
            name='discipline',
        ),
        migrations.RemoveField(
            model_name='semester',
            name='year',
        ),
        migrations.AddField(
            model_name='discipline',
            name='ano',
            field=models.CharField(default=1234, max_length=4),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='semester',
            name='semester',
            field=models.CharField(choices=[('semester_1', 'Semester 1'), ('semester_2', 'Semester 2'), ('semester_3', 'Semester 3'), ('semester_4', 'Semester 4')], max_length=10),
        ),
    ]
