# Generated by Django 4.1.7 on 2023-03-28 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_discipline_semester'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scores',
            name='semester',
        ),
    ]
