# Generated by Django 4.2 on 2023-04-11 00:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0013_remove_scores_semester"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="scores",
            options={},
        ),
        migrations.AlterField(
            model_name="discipline",
            name="student",
            field=models.ManyToManyField(blank=True, null=True, to="core.student"),
        ),
    ]
