# Generated by Django 4.2 on 2023-04-11 00:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0014_alter_scores_options_alter_discipline_student"),
    ]

    operations = [
        migrations.AlterField(
            model_name="discipline",
            name="student",
            field=models.ManyToManyField(blank=True, to="core.student"),
        ),
    ]
