# Generated by Django 4.2 on 2023-05-03 02:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0016_teacher_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="scores",
            old_name="aluno",
            new_name="student",
        ),
    ]
