# Generated by Django 3.1.7 on 2021-03-22 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('To_do_list', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todolist',
            old_name='descriptioin',
            new_name='description',
        ),
    ]
