# Generated by Django 3.1.12 on 2021-07-27 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CadastroForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='fotosCamera/')),
                ('school', models.CharField(choices=[('FR', 'Freshman'), ('JR', 'Junior'), ('SR', 'Senior'), ('GR', 'Graduate')], default='FR', max_length=2)),
                ('isCompleted', models.BooleanField(default=False)),
            ],
        ),
    ]
