# Generated by Django 3.1.12 on 2021-07-27 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_forms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FastCadastro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('sobrenome', models.CharField(max_length=100)),
            ],
        ),
    ]
