# Generated by Django 3.1.12 on 2021-07-28 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_forms', '0002_fastcadastro'),
    ]

    operations = [
        migrations.AddField(
            model_name='fastcadastro',
            name='isCompleted',
            field=models.BooleanField(default=False),
        ),
    ]
