# Generated by Django 3.1.12 on 2021-07-28 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_forms', '0003_fastcadastro_iscompleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='fastcadastro',
            name='image',
            field=models.ImageField(default='123123', upload_to='fotosCamera/'),
            preserve_default=False,
        ),
    ]
